version: "2.4"

services:
  app:
    image: app
    build:
      context: .
      target: dev
    working_dir: /workspace
    volumes:
      # - /workspace/node_modules
      - type: volume
        target: /workspace/node_modules
    command: ["npm", "start"]